### Random Tensor

In [2]:
import torch
torch.__version__



'2.6.0'

In [3]:
scalar = torch.tensor(7)
print(scalar)

print(scalar.ndim)

print(scalar.item())

vector = torch.tensor([7, 7])
print(vector)

print(vector.ndim)

print(vector.shape)

MATRIX = torch.tensor([[7, 8], [9, 10]])
print(MATRIX.ndim)

print(MATRIX.shape)

TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)


tensor(7)
0
7
tensor([7, 7])
1
torch.Size([2])
2
torch.Size([2, 2])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
3
torch.Size([3, 2, 3])


In [4]:
random_tensor = torch.rand(size=(3, 3))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.dtype)

random_image_size_tensor = torch.rand(size=(224, 224, 3))
print(random_image_size_tensor)
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

tensor([[0.2691, 0.9124, 0.8921],
        [0.3872, 0.7809, 0.2780],
        [0.9881, 0.0423, 0.3560]])
2
torch.float32
tensor([[[0.7139, 0.8039, 0.4249],
         [0.2774, 0.5211, 0.9013],
         [0.3512, 0.1650, 0.9508],
         ...,
         [0.9152, 0.5123, 0.3988],
         [0.9314, 0.8936, 0.9760],
         [0.6027, 0.0494, 0.4279]],

        [[0.0510, 0.0444, 0.8544],
         [0.9767, 0.9093, 0.0178],
         [0.4883, 0.7381, 0.8643],
         ...,
         [0.6888, 0.2596, 0.5757],
         [0.6866, 0.3885, 0.9351],
         [0.3478, 0.1676, 0.1629]],

        [[0.5048, 0.2854, 0.0062],
         [0.7356, 0.5703, 0.4403],
         [0.8736, 0.8978, 0.6361],
         ...,
         [0.0525, 0.1370, 0.9542],
         [0.9179, 0.6546, 0.9769],
         [0.5635, 0.8695, 0.7884]],

        ...,

        [[0.3416, 0.2595, 0.1773],
         [0.8063, 0.2030, 0.6189],
         [0.3453, 0.1677, 0.0774],
         ...,
         [0.5456, 0.3817, 0.0925],
         [0.6322, 0.3558, 0.3241],


In [5]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros.dtype)
ones = torch.ones(size=(3, 4))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [6]:
zero_to_ten = torch.arange(0, 10, 1)
print(zero_to_ten)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [8]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

torch.Size([3])
torch.float32
cpu


In [9]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)    # torch.half would also work
print(float_16_tensor.dtype)

torch.float16


In [10]:
some_tensor = torch.rand([1, 2, 3])
print(some_tensor)
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Data type of tensor: {some_tensor.dtype}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[[0.6029, 0.2251, 0.0888],
         [0.7832, 0.8382, 0.2439]]])
Shape of tensor: torch.Size([1, 2, 3])
Data type of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor)

tensor = tensor + 10
print(tensor)
tensor = tensor - 10
print(tensor)
torch.multiply(tensor, 10)
print(tensor)
print(tensor)

print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [16]:
import torch
import time

tensor = torch.tensor([1, 2, 3])
print(tensor.shape)
print(tensor * tensor)

torch.matmul(tensor, tensor)

print(tensor @ tensor)

# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

start_time = time.time()
torch.matmul(tensor, tensor)
print(f"Time taken for matrix multiplication: {time.time() - start_time}")

torch.Size([3])
tensor([1, 4, 9])
tensor(14)
tensor(14)
Time taken for matrix multiplication: 0.0001537799835205078


In [18]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 8], [9, 10], [11, 12]], dtype=torch.float32)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [20]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [21]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])


In [22]:
print(f"Original shape of tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}\n")
print(f"New shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.T.shape}\n")
print(f"Multiplying {tensor_A.shape} with {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shape of tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])

New shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([2, 3])

Multiplying torch.Size([3, 2]) with torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

Output shape: torch.Size([3, 3])


In [23]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [24]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n {output} \n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
 tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>) 

Output shape: torch.Size([3, 6])


In [25]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}")    # This will throw an error
print(f"Mean: {x.type(torch.float32).mean()}")  # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [27]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [28]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Argmax: {tensor.argmax()}")
print(f"Argmin: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Argmax: 8
Argmin: 0


In [30]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [31]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [32]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [33]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [34]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [35]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [36]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [37]:
x_stacked = torch.stack([x, x, x, x], dim=0)    # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [38]:
print(f"Previous tensor: {x.reshape}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: <built-in method reshape of Tensor object at 0x126d8edf0>
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [39]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])

New shape: torch.Size([1, 7])


In [40]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrande the axis order
x_permuted = x_original.permute(2, 0, 1)    # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
# Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor
# and if you change the values in the view, it will change the values of the original

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [41]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [42]:
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket:\n{x[0][0]}")
print(f"Third square bracket:\n{x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:
tensor([1, 2, 3])
Third square bracket:
1


In [43]:
# You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension
x[:, 0]

tensor([[1, 2, 3]])

In [44]:
# Get all values of the 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [45]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [46]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [47]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [48]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [49]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [50]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [51]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A: {random_tensor_A}")
print(f"Tensor B: {random_tensor_B}")
print(f"Does Tensor A equal Tensor B? anywhere")
random_tensor_A == random_tensor_B

Tensor A: tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])
Tensor B: tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])
Does Tensor A equal Tensor B? anywhere


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [52]:
import torch
import random

# That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.
# Set the random seed
RANDOM_SEED = 42    # try changing this to different values and see what happens the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Hava to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)  # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C: {random_tensor_C}")
print(f"Tensor D: {random_tensor_D}")
print(f"Does Tensor C equal Tensor D? anywhere")
random_tensor_C == random_tensor_D

Tensor C: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor D: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Does Tensor C equal Tensor D? anywhere


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])