### Random Tensor

In [1]:
import torch
torch.__version__



'2.6.0'

In [2]:
scalar = torch.tensor(7)
print(scalar)

print(scalar.ndim)

print(scalar.item())

vector = torch.tensor([7, 7])
print(vector)

print(vector.ndim)

print(vector.shape)

MATRIX = torch.tensor([[7, 8], [9, 10]])
print(MATRIX.ndim)

print(MATRIX.shape)

TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)


tensor(7)
0
7
tensor([7, 7])
1
torch.Size([2])
2
torch.Size([2, 2])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
3
torch.Size([3, 2, 3])


In [3]:
random_tensor = torch.rand(size=(3, 3))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.dtype)

random_image_size_tensor = torch.rand(size=(224, 224, 3))
print(random_image_size_tensor)
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

tensor([[0.9538, 0.9072, 0.4745],
        [0.4003, 0.8354, 0.7741],
        [0.7209, 0.6961, 0.8800]])
2
torch.float32
tensor([[[0.0571, 0.7119, 0.3076],
         [0.0650, 0.1132, 0.8895],
         [0.9068, 0.9347, 0.5271],
         ...,
         [0.0960, 0.7121, 0.8099],
         [0.6371, 0.4678, 0.1822],
         [0.0451, 0.9730, 0.5635]],

        [[0.4631, 0.5566, 0.4977],
         [0.7349, 0.9249, 0.0431],
         [0.8535, 0.6499, 0.8388],
         ...,
         [0.3732, 0.8253, 0.4837],
         [0.8469, 0.0964, 0.9650],
         [0.2122, 0.7561, 0.8362]],

        [[0.3458, 0.6170, 0.2273],
         [0.2538, 0.1683, 0.1887],
         [0.2332, 0.0877, 0.3899],
         ...,
         [0.0229, 0.1612, 0.4975],
         [0.6551, 0.1061, 0.1366],
         [0.0432, 0.0441, 0.0224]],

        ...,

        [[0.7063, 0.3432, 0.0527],
         [0.8259, 0.8776, 0.8673],
         [0.4223, 0.4279, 0.2290],
         ...,
         [0.9149, 0.5248, 0.4268],
         [0.9496, 0.0475, 0.5454],


In [4]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros.dtype)
ones = torch.ones(size=(3, 4))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [5]:
zero_to_ten = torch.arange(0, 10, 1)
print(zero_to_ten)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [6]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [7]:
"""
Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & Deep Learning
1. Tensor not right shape
2. Tensor not right datatype
3. Tensor not on the right device
"""
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what dataype is the tensor(e.g. float32, float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operations 
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

torch.Size([3])
torch.float32
cpu


### Getting information from tensors
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [8]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)    # torch.half would also work
print(float_16_tensor.dtype)

torch.float16


In [9]:
some_tensor = torch.rand([1, 2, 3])
print(some_tensor)
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Data type of tensor: {some_tensor.dtype}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[[0.4845, 0.3818, 0.5591],
         [0.9081, 0.5687, 0.6255]]])
Shape of tensor: torch.Size([1, 2, 3])
Data type of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating Tensors (tensor operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [10]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
# Subtract 10
print(tensor - 10)
# Multiply tensor by 10
print(tensor * 10)
print(tensor)

torch.add(tensor, 10)
print(tensor)
tensor = tensor - 10
print(tensor)
# Try out PyTorch in-bulit functions
torch.multiply(tensor, 10)
print(tensor)
print(tensor)

print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([-9, -8, -7])
tensor([-9, -8, -7])
tensor([-9, -8, -7])
tensor([-9, -8, -7]) * tensor([-9, -8, -7])
Equals: tensor([81, 64, 49])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise multiplication
2. Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [11]:
import time

print(tensor * tensor)

torch.matmul(tensor, tensor)

print(tensor @ tensor)

# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

start_time = time.time()
torch.matmul(tensor, tensor)
print(f"Time taken for matrix multiplication: {time.time() - start_time}")

tensor([81, 64, 49])
tensor(194)
tensor(194)
Time taken for matrix multiplication: 4.887580871582031e-05


### One of the most common errors in deep learning: shape errors

In [12]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]], dtype=torch.float32)
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul)
# it won't work
# torch.matmul(tensor_A, tensor_B)

In [13]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


To fix tensor shape issues, we can manipuldate the shape of one of our tensors using a **transpose**.<br/>
A **transpose** switches the axes or dimensions of a given tensor

In [14]:
print(tensor_B)
print(tensor_B.T)

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shape of tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.T.shape}")
print(f"Multiplying {tensor_A.shape} with {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shape of tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([2, 3])
Multiplying torch.Size([3, 2]) with torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [16]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [17]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n {output} \n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
 tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>) 

Output shape: torch.Size([3, 6])


### Find the min, max, mean, sum, etc(tensor aggregation)

In [18]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}")    # This will throw an error
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
print(f"Mean: {x.type(torch.float32).mean()}")  # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [19]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [20]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
# Find the position in the tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
print(f"Argmax: {tensor.argmax()}")
# Find the position in the tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
print(f"Argmin: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Argmax: 8
Argmin: 0


In [21]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [22]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [23]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memoryas the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [24]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [25]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [26]:
# Change the view
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [27]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [28]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)    # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
# torch.squeeze() removes all single dimensions from a target tensor
print(f"Previous tensor: {x.reshape}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: <built-in method reshape of Tensor object at 0x10e4277a0>
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [46]:
## torch.unsqueeze() - adds an single dimension to a target tensor at a specific dim (dimnesion)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension to unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])

New shape: torch.Size([1, 7])


In [ ]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)    # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]
# Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor
# and if you change the values in the view, it will change the values of the original

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [47]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [48]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [49]:
# Let's index on our new tensor
print(f"First square bracket:\n{x[0]}")
# Let's index on the middle bracket (dim=1)
print(f"Second square bracket:\n{x[0][0]}")
# Let's index on the most inner bracket (last dimension)
print(f"Third square bracket:\n{x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:
tensor([1, 2, 3])
Third square bracket:
1


In [ ]:
# you can also use ":"  to select "all" of a target dimension
# You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension
x[:, 0]

tensor([[1, 2, 3]])

In [35]:
# Get all values of the 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [36]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [37]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting form numpy -> pytorch, pytorch reflects numpy's default datatype of float64, unless specified otherwise .type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [52]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [53]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 3., 4., 5., 6., 7., 8.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavor" the randomness.

In [42]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A: {random_tensor_A}")
print(f"Tensor B: {random_tensor_B}")
print(f"Does Tensor A equal Tensor B? anywhere")
random_tensor_A == random_tensor_B

Tensor A: tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])
Tensor B: tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])
Does Tensor A equal Tensor B? anywhere


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# Let's make some random but reproducible tensors
import torch
import random

# That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.
# Set the random seed
RANDOM_SEED = 42    # try changing this to different values and see what happens the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Hava to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)  # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C: {random_tensor_C}")
print(f"Tensor D: {random_tensor_D}")
print(f"Does Tensor C equal Tensor D? anywhere")
random_tensor_C == random_tensor_D

Tensor C: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor D: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Does Tensor C equal Tensor D? anywhere


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])